//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VulkanManaged {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VulkanManaged.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find any device with Vulkan support..
        /// </summary>
        internal static string DeviceNotFound {
            get {
                return ResourceManager.GetString("DeviceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the required (including by the programmer) extensions is not supported..
        /// </summary>
        internal static string ExtensionNotPresent {
            get {
                return ResourceManager.GetString("ExtensionNotPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given queue family index is invalid..
        /// </summary>
        internal static string InvalidQueueFamilyIndex {
            get {
                return ResourceManager.GetString("InvalidQueueFamilyIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given queue family or queue index is invalid..
        /// </summary>
        internal static string InvalidQueueIndex {
            get {
                return ResourceManager.GetString("InvalidQueueIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The QueueInfoMapper function returned an invalid QueueInfo record instance..
        /// </summary>
        internal static string InvalidQueueInfo {
            get {
                return ResourceManager.GetString("InvalidQueueInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the required (including by the programmer) layers is not supported..
        /// </summary>
        internal static string LayerNotPresent {
            get {
                return ResourceManager.GetString("LayerNotPresent", resourceCulture);
            }
        }
    }
}
